In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import scipy.stats as spst
import scipy.integrate as spint
from scipy.optimize import newton
import matplotlib.pyplot as plt
import warnings

#import sys
#sys.path.insert(sys.path.index('')+1, 'D:/Github/PyFeng')
import pyfeng as pf

# Basket Option

In [3]:
sigma = 0.4*np.ones(4)
spot = np.ones(4)*100
texp=5

In [4]:
m = pf.BsmNdMc(sigma, cor=0.5, rn_seed=1234)
m.simulate(tobs = [texp], n_path=10000)
print(m.n_path)
m.path.shape

10000


(1, 10000, 4)

In [5]:
m.simulate(tobs = [texp], n_path=50000, store=2)
print(m.n_path)
print(m.path.shape)

50000
(1, 50000, 4)


In [6]:
# varying strikes
payoff = lambda x: np.fmax(np.mean(x, axis=1) - strike, 0)

strikes = np.arange(50, 151, 10)
price = []
for strike in strikes:
    price.append(m.price_european(spot, texp, payoff))
np.array(price)

array([55.05442979, 48.24139219, 42.29187964, 37.11853211, 32.62517125,
       28.73942945, 25.37967374, 22.46038799, 19.92272369, 17.71628982,
       15.80171962])

In [7]:
# varying forwards
payoff = lambda x: np.fmax(np.mean(x, axis=1) - strike, 0)
strike = 100
price = []
for spot in np.arange(50, 151, 10):
    price.append(m.price_european(spot, texp, payoff))
np.array(price)

array([ 4.6049753 ,  7.87316825, 11.99891419, 16.91824336, 22.53129533,
       28.73942945, 35.47288913, 42.65874825, 50.22366433, 58.11022683,
       66.27677878])

In [8]:
# varying except sigma1=100%
strike = spot = 100
payoff = lambda x: np.fmax(np.mean(x, axis=1) - strike, 0)
price = []
for sigma1 in np.array([5, 10, 15, 20, 30, 40, 50, 60, 70, 80, 100])/100:
    sigma = sigma1 * np.ones(4)
    sigma[0] = 1
    #print(sigma)
    m = pf.BsmNdMc(sigma, cor=0.5, rn_seed=1234)
    m.simulate(tobs = [texp], n_path=400000)
    price.append(m.price_european(spot, texp, payoff))
np.array(price)

array([18.94495855, 20.45829493, 22.49840945, 24.87785108, 30.11378007,
       35.57949546, 41.05473026, 46.42608331, 51.61861158, 56.59050047,
       65.9322128 ])

# Simpon's method for integration

Let's integrate numerically.

$$ \int_0^T exp(-a*t) dt  = \frac{1}{a}(1 - exp(-a T))$$

In [9]:
a = 10
texp = 2
exact = (1 - np.exp(-a*texp))/a
exact

0.09999999979388464

In [10]:
def f(t, a):
    return np.exp(-a*t)

n_step = 100
tobs = np.arange(0, n_step+1)/n_step * texp
simp = spint.simps(f(tobs, a), dx=texp/n_step)
#simp = spint.simps(f(tobs, a), dx=1) * texp/n_step
print(simp, simp-exact)

0.10000088446767287 8.84673788226209e-07


# For SABR Model
## Integration of sigma(t)

In [11]:
# You can use BsmNdMc because sigma_t is also a geometric Brownian motion

vov = 0.3
texp = 5
m = pf.BsmNdMc(vov, rn_seed=1234)
tobs = np.arange(0, 101)/100*texp

In [12]:
_ = m.simulate(tobs = tobs, n_path=1000)

In [13]:
print(m.path.shape)
sigma_path = np.squeeze(m.path)
print(sigma_path.shape)

(101, 1000, 1)
(101, 1000)


In [14]:
sigma_final = sigma_path[-1,:]

In [15]:
int_var = spint.simps(sigma_path**2, dx=1, axis=0)/100
int_var.shape

(1000,)

In [16]:
np.mean(sigma_final)

1.007675560307406