# Correlated (multivariate) normal random variables

In [3]:
import numpy as np

In [6]:
# Sigma (std) and correlation 
sig_v = np.array([2, 5, 2])
cor_m = np.array([[1, 0.7, -0.2], [0.7, 1, 0.5], [-0.2, 0.5, 1]])
print(sig_v, '\n', cor_m)

[2 5 2] 
 [[ 1.   0.7 -0.2]
 [ 0.7  1.   0.5]
 [-0.2  0.5  1. ]]


### Construct Covariance Matrix

In [5]:
cov_m = sig_v * cor_m * np.reshape(sig_v,(3,1))
print(cov_m)

[[ 4.   7.  -0.8]
 [ 7.  25.   5. ]
 [-0.8  5.   4. ]]


### Cholesky decomposition of covariance matrix

In [9]:
chol_m = np.linalg.cholesky(cov_m)
print(chol_m)

[[ 2.          0.          0.        ]
 [ 3.5         3.57071421  0.        ]
 [-0.4         1.79235851  0.79211803]]


In [10]:
# Let's verify that L x L^T = Covariance

print( chol_m @ chol_m.transpose(), '\n' )
print( chol_m @ chol_m.transpose() - cov_m )

[[ 4.   7.  -0.8]
 [ 7.  25.   5. ]
 [-0.8  5.   4. ]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# Now let's create multivariate normal random variables following the covariance matrix
# First, create standard normals (1000x3)

znorm_m = np.random.normal(size=(3, 10000))
znorm_m

array([[-1.37046023,  0.86956376, -0.63140452, ..., -0.69904821,
        -0.24070039,  0.21470762],
       [-1.76507528, -1.08103786,  1.75530624, ..., -0.43042879,
        -0.6837158 ,  1.90447716],
       [ 0.37168667,  0.83320175, -0.17904995, ..., -0.7465378 ,
        -0.10368163, -1.4164211 ]])

In [18]:
np.cov(znorm_m)

array([[ 0.99188171, -0.00483866, -0.01526465],
       [-0.00483866,  0.99756529,  0.02105408],
       [-0.01526465,  0.02105408,  0.99980028]])

In [19]:
# Then multiply C^T

#xnorm_m = znorm_m @ chol_m.transpose()
xnorm_m = chol_m @ znorm_m
xnorm_m

array([[ -2.74092047,   1.73912753,  -1.26280904, ...,  -1.39809643,
         -0.48140078,   0.42941524],
       [-11.0991902 ,  -0.81660407,   4.05778112, ...,  -3.98360696,
         -3.28380509,   7.55182034],
       [ -2.32104388,  -1.62543877,   3.25687118, ...,  -1.08320948,
         -1.21131177,   2.20565009]])

In [21]:
# Let's verify that X = C * Z  follows the covariance
print(cov_m)
cov_m_sample = np.cov( xnorm_m )
print( 'Cov from sample:\n', cov_m_sample )
print( 'Error of Cov matrix:\n', cov_m_sample - cov_m )

[[ 4.   7.  -0.8]
 [ 7.  25.   5. ]
 [-0.8  5.   4. ]]
Cov from sample:
 [[ 3.96752684  6.90861707 -0.83503339]
 [ 6.90861707 24.74856623  4.98957033]
 [-0.83503339  4.98957033  4.0671488 ]]
Error of Cov matrix:
 [[-0.03247316 -0.09138293 -0.03503339]
 [-0.09138293 -0.25143377 -0.01042967]
 [-0.03503339 -0.01042967  0.0671488 ]]


In [22]:
# also check the correation
print(cor_m)
cor_m_sample = np.corrcoef( xnorm_m )
print( 'Corr from sample:\n', cor_m_sample )
print( 'Error:\n', cor_m_sample - cor_m )

[[ 1.   0.7 -0.2]
 [ 0.7  1.   0.5]
 [-0.2  0.5  1. ]]
Corr from sample:
 [[ 1.          0.69719805 -0.20787338]
 [ 0.69719805  1.          0.49732821]
 [-0.20787338  0.49732821  1.        ]]
Error:
 [[-1.11022302e-16 -2.80195240e-03 -7.87337922e-03]
 [-2.80195240e-03  0.00000000e+00 -2.67178881e-03]
 [-7.87337922e-03 -2.67178881e-03  0.00000000e+00]]
