# Basket option implementation based on normal model

In [56]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [57]:
import numpy as np
#import option_models as opt
from option_models import basket
from option_models import bsm
from option_models import normal

In [58]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([0, 1, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

In [59]:
cor_m

array([[1. , 0.5, 0.5, 0.5],
       [0.5, 1. , 0.5, 0.5],
       [0.5, 0.5, 1. , 0.5],
       [0.5, 0.5, 0.5, 1. ]])

In [60]:
print(weights)

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket)

[0 1 0 0]
26.92956987643586


In [61]:
# Compare the price to normal model formula

norm1 = normal.NormalModel(vol=40, intr=0, divr = 0)
price_norm = norm1.price(strike=120, spot=100, texp=texp, cp=1)
print(price_basket, price_norm)

26.92956987643586 26.570845957870503


In [62]:
# A trivial test case 2
# all assets almost perfectly correlated:
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.0001*np.identity(4) + 0.9999*np.ones((4,4))
texp = 5
strike = 120

print( cor_m )

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket, price_norm)

[[1.     0.9999 0.9999 0.9999]
 [0.9999 1.     0.9999 0.9999]
 [0.9999 0.9999 1.     0.9999]
 [0.9999 0.9999 0.9999 1.    ]]
26.761395615904505 26.570845957870503


In [63]:
# A full test set for basket option with exact price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 100
price_exact = 28.0073695

In [64]:
cor_m

array([[1. , 0.5, 0.5, 0.5],
       [0.5, 1. , 0.5, 0.5],
       [0.5, 0.5, 1. , 0.5],
       [0.5, 0.5, 0.5, 1. ]])

In [65]:
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket, price_exact)

28.168716545630815 28.0073695


# [To Do] Basket option implementation based on BSM model
## Write the similar test for BSM

In [66]:
price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
print(price_basket)

28.27745472325051


In [67]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

print(weights)

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
print(price_basket)
print(normal.normal_formula(strike=120, spot=100, vol=0.4, texp=5))

[1 0 0 0]
28.751631082489702
1.8935501738856734e-112


# Spread option implementation based on normal model

In [68]:
# A full test set for spread option

spot = np.array([100, 96])
vol = np.array([0.2, 0.1])
weights = np.array([1, -1])
divr = np.array([1, 1])*0.05
intr = 0.1
cor_m = np.array([[1, 0.5], [0.5, 1]])
texp = 1
strike = 0
price_exact = 8.5132252

In [69]:
# MC price based on normal model
# make sure that the prices are similar

np.random.seed(123456)
price_spread = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=False)
print(price_spread, price_exact)

8.348852807225292 8.5132252


# Spread option implementation based on BSM model

In [70]:
# Once the implementation is finished the BSM model price should also work
np.random.seed(123456)
price_spread = basket.basket_price_mc(
    strike, spot, vol, weights, texp, cor_m, intr=intr, divr=divr, bsm=True)

In [71]:
price_spread

8.525394174202468

In [72]:
# You also test Kirk's approximation
price_kirk = basket.spread_price_kirk(strike, spot, vol, texp, 0.5, intr, divr)
print(price_kirk, price_spread)

8.5132252295455 8.525394174202468


# [To Do] Complete the implementation of basket_price_norm_analytic
# Compare the MC stdev of BSM basket prices from with and without CV

In [73]:
# The basket option example from above
spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 1, 1, 1])/4
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120
cp = 1
n_samples = 10000

In [74]:
price1 = basket.basket_price_mc(
        strike, spot, vol, weights, texp, cor_m,
        intr, divr, cp, True, n_samples)
print(price1)

21.010383316187788


In [75]:
price2 = basket.basket_price_mc(
        strike, spot, spot*vol, weights, texp, cor_m,
        intr, divr, 1, False, 10000)
print(price2)

19.3338717194432


In [76]:
### Make sure that the analytic normal price is correctly implemented
price3 = basket.basket_price_norm_analytic(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr)
print(price3)

[19.33039557 19.33039557 19.33039557 19.33039557]


In [77]:
# Run below about 100 times and get the mean and stdev

### Returns 2 prices, without CV and with CV 
price_basket = basket.basket_price_mc_cv(strike, spot, vol, weights, texp, cor_m)
print(price_basket)

[22.67017605 22.49790555]


In [78]:
prices_cv = []
prices_no_cv = []
for i in range(100):
    temp = basket.basket_price_mc_cv(strike, spot, vol, weights, texp, cor_m)
    prices_no_cv.append(temp[0])
    prices_cv.append(temp[1])
prices_cv_std = np.std(prices_cv, ddof = 1)
prices_cv_mean = np.mean(prices_cv)
prices_no_cv_std = np.std(prices_no_cv, ddof = 1)
prices_no_cv_mean = np.mean(prices_no_cv)
print('Mean of BasketPrices without CV is %f '% prices_no_cv_mean,'\n' ,' S.E. of BasketPrices without CV is %f' % prices_no_cv_std)
print('\n')
print('Mean of BasketPrices with CV is %f '% prices_cv_mean,'\n' ,' S.E. of BasketPrices with CV is %f' % prices_cv_std)

Mean of BasketPrices without CV is 21.698581  
  S.E. of BasketPrices without CV is 0.637213


Mean of BasketPrices with CV is 21.740592  
  S.E. of BasketPrices with CV is 0.370115
